### ISSUE TITLE
What does norm mean in your paper?

### ISSUE THREAD

**Issue by drscopus** [TimingSpace/MVOScaleRecovery#2]
road norm, region norm, etc. 
I googled it and found an interpretation in https://en.wikipedia.org/wiki/Norm_(mathematics)#Other_norms 
But I don't think the interpretation in above link is the right one.
Please tell me , thank you!

**Comment by TimingSpace** [comment]
Hi, sorry for the late reply,  both of road norm and region norm refer to the normal vector in geometry.
[https://en.wikipedia.org/wiki/Normal_(geometry)](https://en.wikipedia.org/wiki/Normal_(geometry))
Thank you for your interest.
